# Generated by Django 4.2.7 on 2025-09-16 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0001_initial'),
        ('chat_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='typingindicator',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.conversation'),
        ),
        migrations.AddField(
            model_name='typingindicator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlineuser',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_app.chatroom'),
        ),
        migrations.AddField(
            model_name='onlineuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_status', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='messagedeliverystatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.message'),
        ),
        migrations.AddField(
            model_name='messagedeliverystatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.conversation', verbose_name='conversation'),
        ),
        migrations.AddIndex(
            model_name='typingindicator',
            index=models.Index(fields=['user', 'conversation'], name='typing_indi_user_id_adb8c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='typingindicator',
            constraint=models.UniqueConstraint(fields=('user', 'conversation'), name='unique_typing_per_conversation'),
        ),
        migrations.AddIndex(
            model_name='onlineuser',
            index=models.Index(fields=['user', 'current_room'], name='online_user_user_id_f0101b_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagedeliverystatus',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_message_user_status'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['conversation'], name='chat_room_convers_d7cc12_idx'),
        ),
    ]
